### ISSUE TITLE
Home Assistant MQTT discovery

### ISSUE THREAD

**Issue by escoand** [thanksmister/wallpanel-android#118]
I would like to request MQTT discovery feature so that you don't need to add all these sensors by hand.
https://www.home-assistant.io/docs/mqtt/discovery/

Don't know if other home automation systems understand this as well or if jeu have similar interfaces...

**Comment by escoand** [comment]
@thanksmister This should be the correct payload for all the sensors.

```yaml
homeassistant/sensor/<UNIQUEID>/battery/config
{
  "name": "Battery Level",
  "state_topic": "<PREFIX>sensor/battery",
  "unit_of_measurement": "%",
  "value_template": "{{value_json.value}}",
  "unique_id": "wallpanel.<UNIQUEID>.battery",
  "device_class": "battery",
  "device": {
    "name": "WallPanel",
    "identifiers": "wallpanel.<UNIQUEID>",
    "manufacturer": "ThanksMister LLC",
    "model": "WallPanel",
    "sw_version": "<VERSION>"
  }
}


homeassistant/sensor/<UNIQUEID>/temperature/config
{
  "name": "Temperature",
  "state_topic": "<PREFIX>sensor/temperature",
  "unit_of_measurement": "°C",
  "value_template": "{{value_json.value}}",
  "unique_id": "wallpanel.<UNIQUEID>.temperature",
  "device_class": "temperature",
  "device": {
    "name": "WallPanel",
    "identifiers": "wallpanel.<UNIQUEID>",
    "manufacturer": "ThanksMister LLC",
    "model": "WallPanel",
    "sw_version": "<VERSION>"
  }
}


homeassistant/sensor/<UNIQUEID>/light/config
{
  "name": "Light",
  "state_topic": "<PREFIX>sensor/light",
  "unit_of_measurement": "lx",
  "value_template": "{{value_json.value}}",
  "unique_id": "wallpanel.<UNIQUEID>.light",
  "device_class": "illuminance",
  "device": {
    "name": "WallPanel",
    "identifiers": "wallpanel.<UNIQUEID>",
    "manufacturer": "ThanksMister LLC",
    "model": "WallPanel",
    "sw_version": "<VERSION>"
  }
}


homeassistant/sensor/<UNIQUEID>/magneticField/config
{
  "name": "Magnetic Field",
  "state_topic": "<PREFIX>sensor/magneticField",
  "unit_of_measurement": "uT",
  "value_template": "{{value_json.value}}",
  "unique_id": "wallpanel.<UNIQUEID>.magneticField",
  "device": {
    "name": "WallPanel",
    "identifiers": "wallpanel.<UNIQUEID>",
    "manufacturer": "ThanksMister LLC",
    "model": "WallPanel",
    "sw_version": "<VERSION>"
  }
}


homeassistant/sensor/<UNIQUEID>/pressure/config
{
  "name": "Pressure",
  "state_topic": "<PREFIX>sensor/pressure",
  "unit_of_measurement": "hPa",
  "value_template": "{{value_json.value}}",
  "unique_id": "wallpanel.<UNIQUEID>.pressure",
  "device_class": "pressure",
  "device": {
    "name": "WallPanel",
    "identifiers": "wallpanel.<UNIQUEID>",
    "manufacturer": "ThanksMister LLC",
    "model": "WallPanel",
    "sw_version": "<VERSION>"
  }
}


homeassistant/binary_sensor/<UNIQUEID>/motion/config
{
  "name": "Motion",
  "state_topic": "<PREFIX>sensor/motion",
  "payload_on": "{\"value\":true}",
  "payload_off": "{\"value\":false}",
  "unique_id": "wallpanel.<UNIQUEID>.motion",
  "device_class": "motion",
  "device": {
    "name": "WallPanel",
    "identifiers": "wallpanel.<UNIQUEID>",
    "manufacturer": "ThanksMister LLC",
    "model": "WallPanel",
    "sw_version": "<VERSION>"
  }
}


homeassistant/binary_sensor/<UNIQUEID>/face/config
{
  "name": "Face Detected",
  "state_topic": "<PREFIX>sensor/face",
  "payload_on": "{\"value\":true}",
  "payload_off": "{\"value\":false}",
  "unique_id": "wallpanel.<UNIQUEID>.face",
  "device": {
    "name": "WallPanel",
    "identifiers": "wallpanel.<UNIQUEID>",
    "manufacturer": "ThanksMister LLC",
    "model": "WallPanel",
    "sw_version": "<VERSION>"
  }
}


homeassistant/binary_sensor/<UNIQUEID>/qrcode/config
{
  "name": "QR Code",
  "state_topic": "<PREFIX>sensor/qrcode",
  "payload_on": "{\"value\":true}",
  "payload_off": "{\"value\":false}",
  "unique_id": "wallpanel.<UNIQUEID>.qrcode",
  "device": {
    "name": "WallPanel",
    "identifiers": "wallpanel.<UNIQUEID>",
    "manufacturer": "ThanksMister LLC",
    "model": "WallPanel",
    "sw_version": "<VERSION>"
  }
}
```
