### ISSUE TITLE
Options to turn off display at night?

### ISSUE THREAD

**Issue by adangster1** [thanksmister/wallpanel-android#179]
The screen saver keeps the screen On all the time. Is it possible give user option to turn off usage/screen between 11pm and 6am for example?..save some energy and wear on the screen..maybe put the display to sleep mode during this time (no face or motion detection needed during sleep time)

I think I can use Automate app to control the screen off during bedtime but having this build into Wallpanel is more efficient and useful feature.

Thank you for your consideration.

**Comment by nagyrobi** [comment]
+1

**Comment by thanksmister** [comment]
That is a tough request, turning off the screen.  I am sure you can dim the screen to 0, but this is not the same as turning off the screen.  If you turn of the screen, I assume this is the same as locking the screen.  The application might not work since the app is designed to run in the foreground and the screen not locked, so it can receive MQTT messages.   

Have you seen what actually happens if you turn off the screen using Automate?  Does it dim or turn of the screen, does the device wake up when you approach it, or you have to turn in on with the power button?

**Comment by adangster1** [comment]
Hi 
Thank you for the explanation.  Automateit issued a screen lock cmd which turn off the screen..same as push power button..since I dont have the screen  lock enabled..Wallpanel will still wake up screen when motion/face detected.

I did a little digging...
a) turn off motion,face,clock saver..push power button..screen will remained off..as expected..so it can go off at least. 
b) screen off via automateit/or p manual push power button works for me because at the time..the home is dark ..so the wake up sensor is not working  anyway

>>thinking out-loud
..possible implementation are:

>>turn off sensor detection when night time....then let's screen naturally turn off via auto screen timeout...need to use automateit or something to wake up screen next day? Or reenable motion sensor..not sure if this is a good option

Or
>>I have to root my tablet..kill the Wallpanel and start it the next day

Or
>> auto stop/exit app or quit app at certain  time and user can use automateit to start the app next day..which not need root.

**Comment by nagyrobi** [comment]
Currently I've done it this way.
- tablet using static DHCP address from router
- tablet rooted
- installed SSHelper app, this creates an SSH server in Android
- created a script on my linux box to log in to the tabled and toggle the screen:
```
#!/bin/sh
sshpass -p PASSWORD ssh user@TABLED_IP_ADDRESS -p 2222 << EOF
su
input keyevent 26
exit
EOF
```
This script has to be installed in such a way that Home Assistant can run it. That depends on the particular installation environment. I used `shell_command`. Other Home Assistant things:

- an MQTT sensor to detect the screenon state:
```
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/state"
  name: "mywallpanel screenon"
  value_template: '{{ value_json.screenOn }}'
```

- a binary sensor to convert the state to real on/off values:
```
- platform: template
  sensors:
    wallpanel_mywallpanel:
      friendly_name: "MyWallpanel state"
      value_template: "{{ states('sensor.mywallpanel_screenon') }}"
```

- a template switch to turn the screen on and off:
```
- platform: template
  switches:
    wallpanel_nappali:
      friendly_name: "MyWallpanel screen switch"
      value_template: "{{ is_state('binary_sensor.wallpanel_mywallpanel', 'on') }}"
      turn_on:
        - service: mqtt.publish #this wakes the panel
          data:
            topic: wallpanel/mywallpanel/command
            payload: '{"wake":true}'
      turn_off:
        - service: shell_command.toggle_mywallpanel #this triggers the script to toggle from on to off
```

- some automations to turn it off and on at desired moments:
```
- alias: "Wallpanel MyWallpanel ON"
  trigger:
    - platform: time
      at: '06:10:00'
  condition:
    - condition: state
      entity_id: 'binary_sensor.wallpanel_mywallpanel'
      state: 'off'
  action:
    - service: mqtt.publish
      data:
        topic: wallpanel/mywallpanel/command
        payload: '{"wake":true}'

- alias: "Wallpanel MyWallpanel OFF"
  trigger:
    - platform: time
      at: '22:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.wallpanel_mywallpanel
      state: 'on'
  action:
    - service: shell_command.toggle_mywallpanel 

- alias: "Wallpanel MyWallpanel reload"
  trigger:
    - platform: time
      at: '06:10:05'
  action:
    - service: mqtt.publish
      data:
        topic: wallpanel/mywallpanel/command
        payload: '{"clearCache":true, "relaunch":true}'

```

Because wallpanel app doesn't send an MQTT update about the state right after detecting screen state change, the switch will bounce once until the MQTT state arrives. 

It could be done that wallpanel sends and extra MQTT state update in such cases...
