### ISSUE TITLE
Update Websites Documentation

### ISSUE THREAD

**Issue by lied** [thanksmister/wallpanel-android#221]
Hi just a small note, that the config on the website for MQTT Home Assistant didn't work for me.

```yaml
sensor:
  - platform: mqtt
    state_topic: "wallpanel/mywallpanel/sensor/battery"
    name: "WallPanel Battery Level"
    unit_of_measurement: "%"
    value_template: ''
```

The value template doesn't work like this for me. It needs to look like this
` value_template: '{{value_json.value}}'`
