### ISSUE TITLE
REST implementation to power off the display

### ISSUE THREAD

**Issue by tringler** [thanksmister/wallpanel-android#37]
**Is your feature request related to a problem? Please describe.**
I would really like to have a REST option to power off the display. It is not a problem, but it would nice to have it, that i.e. I can power off the screen with my bulbs - Example HASS automation:

```
- alias: floor_light_turn_off_floorled_by_motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00016db094
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001a24994
      from: 'on'
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d00016db094
        state: 'off'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d0001a24994
        state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_286c0788b78a
    - service: switch.turn_off
      entity_id: switch.floor_wallpanel_wakeup
```

**Describe the solution you'd like**
I want to have a REST implementation to power off the display like `curl -H 'Content-Type: application/json' -X POST -d {wake:false} http://192.168.1.251:2971/api/command`

**Describe alternatives you've considered**
Waiting until the device turns off automatically

Thanks in Advance, Thomas
