### ISSUE TITLE
Add other sensors to REST api

### ISSUE THREAD

**Issue by nzhook** [thanksmister/wallpanel-android#44]
**Is your feature request related to a problem? Please describe.**
I don't have a MQTT server currently but Home Assistant provides the [rest sensors](https://www.home-assistant.io/components/sensor.rest/) which could be used to obtain the sensor data.
However when calling the REST api on http://192.168.1.101:2971/api/state only the currentUrl, screenOn and brightness values are returned, however when sensors are enabled additional data such as Battery level, Temperature is provided to MQTT.

**Describe the solution you'd like**
If sensors are enabled the REST API would also return the sensor data.

Option I see would be to add the additional sensors to the following in WallPanelService.kt
```
    private val state: JSONObject
        get() {
            Timber.d("getState")
            val state = JSONObject()
            try {
                state.put(MqttUtils.STATE_CURRENT_URL, appLaunchUrl)
                state.put(MqttUtils.STATE_SCREEN_ON, isScreenOn)
                state.put(MqttUtils.STATE_BRIGHTNESS, screenBrightness)
            } catch (e: JSONException) {
                e.printStackTrace()
            }
            return state
        }
```

Would also be nice to have motion and face detection in here (maybe clearing the flag on next call or after a timeout period) as while this wouldn't be as fast it would save on needing to implement an outbound rest/service call.

PS. Basic example for Home Assistant using the currently available values in the REST API
```
sensor:
  - platform: rest
    name: Front Door tablet screen
    resource: http://192.168.1.101:2971/api/state
    value_template: '{{ value_json.screenOn }}'
    json_attributes:
      - brightness
      - currentUrl

camera:
  - platform: mjpeg
    name: Front Door tablet
    mjpeg_url: http://192.168.1.101:2971/camera/stream
```
